In [82]:
import pandas as pd
stats = pd.read_json('results.json').sort_values('MAPE-mean')
stats = stats[stats.est_type == 'xgboost']
stats.T[stats.nunique() > 1]

,3,8,4,9,1,2,13,10,5,0
MAPE-mean,0.0815279,0.0841075,0.089512,0.0951765,0.100802,0.115526,0.120321,0.126246,0.18851,0.189893
MAPE-std,0.00207426,0.00253239,0.00514491,0.00784125,0.00297206,0.00485698,0.00786869,0.00954889,0.0900312,0.0160805
bagging,False,False,False,True,False,False,False,False,False,False
colsample_bytree,0.3,0.3,0.3,0.3,0.5,0.5,0.3,0.3,0.3,0.5
es_share,0,0,0,0,0.05,0,0,0.05,0,0.2
eta,0.01,0.01,0.05,0.05,0.01,0.05,0.05,0.05,0.05,0.1
exec-time-sec,467.352,693.359,82.7434,876.678,1551.09,73.863,866.465,158.828,101.357,53.5374
max_depth,10,10,10,10,10,10,10,10,10,4
num_es_rounds,50,50,50,50,50,50,50,50,50,120
num_parallel_tree,2,2,2,2,2,2,2,2,2,1
num_rounds,5000,5000,1000,1000,10000,1000,1000,5000,1000,10000
objective,poisson,poisson,poisson,poisson,mape,mape,poisson,poisson,poisson,linear
per_group_regr,False,False,False,False,False,False,True,False,False,False
transf_type,drop,union,drop,dr+inp,drop,drop,dr+inp+sc,poly_kbest,dr+inp+sc+pca,drop

In [83]:
import pandas as pd
stats = pd.read_json('results.json').sort_values('MAPE-mean')
stats = stats[stats.est_type != 'xgboost']
stats.T[stats.nunique() > 1]

                        6          11         12             7
MAPE-mean         0.113272   0.287046   0.296551       0.403583
MAPE-std        0.00501539  0.0499242   0.034897      0.0333606
alpha                  NaN         10        0.5            NaN
es_share              0.05       0.05          0           0.05
est_type           exttree      ridge   gblinear             gp
eta                    0.1        0.1       0.01            0.1
exec-time-sec      974.134    6.17789    26.4488        28.1572
num_rounds           10000      10000        100          10000
per_group_regr       False       True       True          False
transf_type         dr+inp  dr+inp+sc  dr+inp+sc  dr+inp+sc+pca